DECLARE
name Char(10);
no int;
TOTMARK NUMBER(5,2);
BEGIN
Select rollno,name,(mark1+mark2+mark3) into No,Name, TOTMARK from stud where
rollno=&amp;no;
IF TOTMARK &gt;=250 THEN
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
DBMS_OUTPUT.PUT_LINE(‘ ROLL NO :&#39;||no);
DBMS_OUTPUT.PUT_LINE(&#39; STUDENT NAME :&#39;|| name);
DBMS_OUTPUT.PUT_LINE(&#39; TOTAL MARK :&#39;|| TOTMARK);
DBMS_OUTPUT.PUT_LINE(&#39; GRADE :DISTINCTION’);
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
ELSE IF TOTMARK &lt;250 AND TOTMARK &gt;=180 THEN
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
DBMS_OUTPUT.PUT_LINE(‘ROLL NO :&#39;||no);
DBMS_OUTPUT.PUT_LINE(&#39; STUDENT NAME :&#39;|| name);
DBMS_OUTPUT.PUT_LINE(&#39; TOTAL MARK :&#39;|| TOTMARK);
DBMS_OUTPUT.PUT_LINE(&#39; GRADE :First Class’);
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
ELSE IF TOTMARK &lt;=179 AND TOTMARK &gt;=120 THEN
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
DBMS_OUTPUT.PUT_LINE(‘ROLL NO :&#39;||no);
DBMS_OUTPUT.PUT_LINE(&#39; NAME :&#39;|| name);
DBMS_OUTPUT.PUT_LINE(&#39; TOTAL MARK :&#39;|| TOTMARK);
DBMS_OUTPUT.PUT_LINE(&#39; GRADE :SECOND Class’);
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
ELSE
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
DBMS_OUTPUT.PUT_LINE(‘ROLL NO :&#39;||no);
DBMS_OUTPUT.PUT_LINE(&#39; NAME :&#39;|| name);
DBMS_OUTPUT.PUT_LINE(&#39; TOTAL MARK :&#39;|| TOTMARK);
DBMS_OUTPUT.PUT_LINE(&#39;FAILED &#39;);
DBMS_OUTPUT.PUT_LINE (&#39; &#39;);
END IF;
END IF;
END IF;
END;
/
